# configuration for https://ohi-science.nceas.ucsb.edu/abw_app
study_area:       Belize
git_owner:        OHI-Science
git_repo:         abw
git_slug:         OHI-Science/abw
git_url:          https://github.com/OHI-Science/abw
app_url:          https://ohi-science.nceas.ucsb.edu/abw_app
default_branch:   published
default_scenario: subcountry2014
debug:            False
last_updated:     2015-03-23
ohicore_app:
  git_owner: jules32
  git_repo: abw
  git_branch: draft
  git_commit: moving App to NCEAS server

tabs_hide:        
- Calculate
- Report

