# configuration for https://ohi-science.nceas.ucsb.edu/abw
study_area:       Aruba
git_owner:        OHI-Science
git_repo:         abw
git_slug:         OHI-Science/abw
git_url:          https://github.com/OHI-Science/abw
app_url:          http://ohi-science.nceas.ucsb.edu/abw
default_branch:   published
default_scenario: subcountry2014
debug:            False
last_updated:     2015-04-20
ohicore_app:
  git_owner: ohi-science
  git_repo: ohicore
  git_branch: dev
  git_commit: a1e9d2cdd8ddefb0e9c359dbae62baef08e28ecd

tabs_hide:        
- Calculate
- Report

